name: Download Godot source code


description: Download and extract the Godot source code for use in compiling


inputs:
  version:
    description: Version of Godot source code to download
    default: "3.5.3-stable"


runs:
  using: "composite"

  steps:
    - name: Download and extract Godot
      shell: bash
      run: |
        curl -fLO https://github.com/godotengine/godot/archive/${{ inputs.version }}.tar.gz
        tar -xvzf ${{ inputs.version }}.tar.gz --strip-components 1 --exclude=".github"