name: Download Godot-CPP source code


description: Download and extract the Godot-CPP source code for use in compiling


inputs:
  version:
    description: Version of Godot-CPP source code to download
    default: "4.1"


runs:
  using: "composite"

  steps:
      - name: Get Godot-CPP 4.1 (For Godot 4.1-4.2)
        if: ${{ inputs.version == '4.1' }}
        shell: sh
        run: |
          git submodule update --init --recursive

      - name: Get Godot-CPP 4.3 (For Godot 4.3+)
        if: ${{ inputs.version == '4.3' }}
        shell: sh
        run: |
          rm .gitmodules
          mv .gitmodules43 .gitmodules
          git submodule sync
          git submodule update --init --recursive