#ifndef GODOTSTEAM_CONSTANTS_H
#define GODOTSTEAM_CONSTANTS_H


#define MAX_MESSAGE_COUNT 255
#define MAX_TIME_WITHOUT_MESSAGE 1000
#define STEAM_BUFFER_SIZE 255 //deprecated?


#endif // GODOTSTEAM_MULTIPLAYER_PEER_H