#ifndef GODOTSTEAMMULTIPLAYER_REGISTER_TYPES_H
#define GODOTSTEAMMULTIPLAYER_REGISTER_TYPES_H

#include "modules/register_module_types.h"

void initialize_godotsteammultiplayer_module(ModuleInitializationLevel level);
void uninitialize_godotsteammultiplayer_module(ModuleInitializationLevel level);

#endif