name: Download and Install Vulkan SDK


description: Download and install the Vulkan Molten SDK


runs:
  using: "composite"

  steps:
    - name: Download and Install
      shell: bash
      run: |
        set -euo pipefail
        IFS=$'\n\t'

        # Download and install the Vulkan SDK.
        curl -L "https://sdk.lunarg.com/sdk/download/1.3.268.1/mac/vulkansdk-macos-1.3.268.1.dmg" -o /tmp/vulkan-sdk.dmg

        hdiutil attach /tmp/vulkan-sdk.dmg -mountpoint /Volumes/vulkan-sdk
        /Volumes/vulkan-sdk/InstallVulkan.app/Contents/MacOS/InstallVulkan \
            --accept-licenses --default-answer --confirm-command install
        cnt=5

        until hdiutil detach -force /Volumes/vulkan-sdk
        do
          [[ cnt -eq "0" ]] && break
          sleep 1
          ((cnt--))
        done

        rm -f /tmp/vulkan-sdk.dmg
        echo 'Vulkan SDK installed successfully!'