name: Upload Steam Redistributable


description: Upload the Steam redistributable file for packaging


inputs:
  name:
    description: The artifact name
    required: true
    default: false

  path:
    description: Path to the redistributable
    required: true
    default: ""

  redist:
    description: Redistributable file's name
    required: true
    default: "steam_api.dll"


runs:
  using: "composite"

  steps:
    - name: Upload Steam Redistributable
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ./modules/godotsteam/sdk/redistributable_bin/${{ inputs.path}}${{ inputs.redist }}
        overwrite: true
        retention-days: 14